### ISSUE TITLE
[Bug]: Motor Stream State Errors

### ISSUE THREAD

**Issue by shaoshuaizyk** [farm-ng/farm-ng-amiga#105]
### Describe the bug

Hi, I have followed the tutorial [here](https://amiga.farm-ng.com/docs/examples/motor_state/motor-state) but saw the following errors:

<AioRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Method not found!"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-04-20T22:20:36.481724637-07:00", grpc_status:12, grpc_message:"Method not found!"}"

### Relevant Versions

farm-ng-amiga == 0.0.6 and 0.0.9 both show the error
dashboard firmware v0.1.9
farm-ng-amiga git commit: commit 71a0445369ea1d9dbc4cac21510d870c2abf1f83 (HEAD -> main, origin/main, origin/HEAD)

### Reproduction steps

```bash
SSH to amiga by wifi, git clone the farm-ng-amiga code, then:
1. Create virtual environment:
cd farm-ng-amiga
python3 -m venv venv
source venv/bin/activate
2. Install
cd py/examples/motor_states_stream
pip install -r requirements.txt
3.python main.py --canbus-port 50060
```

### Expected behavior

It shows the state of the motor.

**Comment by Hackerman342** [comment]
Hello @shaoshuaizyk,

Can you please share/describe what you see for current version on the `System Updates` tab of the :gear: Settings page (:gear: > `System Updates`)?

My hunch is your brain OS is on a version before the `streamMotorStates` rpc as implemented in the canbus service. This is a prerequisite for using the `streamMotorStates` rpc method from a client of that service.
 
If you do not see a current version, or do not even have a `System Updates` tab, then this is likely the case.

You can see instructions for upgrading to `v1.2.2` here: [**farm-ng Discourse - v1.2.0 Released**](https://discourse.farm-ng.com/t/amigaos-v1-2-0-released/160)

System Updates tab example:
![Screenshot from 2023-04-21 07-28-40](https://user-images.githubusercontent.com/53625197/233625556-a308183d-c02b-4153-86be-990d2919b163.png)

**Comment by shaoshuaizyk** [comment]
> Hello @shaoshuaizyk,
> 
> Can you please share/describe what you see for current version of your brain, found on the `System Updates` tab of the ⚙️ Settings page (⚙️ > `System Updates`)?
> 
> My hunch is your brain OS is on a version before the `streamMotorStates` rpc as implemented in the canbus service. This is a prerequisite for using the `streamMotorStates` rpc method from a client of that service.
> 
> If you do not see a current version, or do not even have a `System Updates` tab, then this is likely the case.
> 
> You can see instructions for upgrading to `v1.2.2` here: [**farm-ng Discourse - v1.2.0 Released**](https://discourse.farm-ng.com/t/amigaos-v1-2-0-released/160)
> 
> System Updates tab example: ![Screenshot from 2023-04-21 07-28-40](https://user-images.githubusercontent.com/53625197/233625556-a308183d-c02b-4153-86be-990d2919b163.png)

Thanks for the reply! I will check our AmigaOS version. Will the update clear our current code in Amiga?

**Comment by shaoshuaizyk** [comment]
> Hello @shaoshuaizyk,
> 
> 
> 
> Can you please share/describe what you see for current version of your brain, found on the `System Updates` tab of the :gear: Settings page (:gear: > `System Updates`)?
> 
> 
> 
> My hunch is your brain OS is on a version before the `streamMotorStates` rpc as implemented in the canbus service. This is a prerequisite for using the `streamMotorStates` rpc method from a client of that service.
> 
>  
> 
> If you do not see a current version, or do not even have a `System Updates` tab, then this is likely the case.
> 
> 
> 
> You can see instructions for upgrading to `v1.2.2` here: [**farm-ng Discourse - v1.2.0 Released**](https://discourse.farm-ng.com/t/amigaos-v1-2-0-released/160)
> 
> 
> 
> System Updates tab example:
> 
> ![Screenshot from 2023-04-21 07-28-40](https://user-images.githubusercontent.com/53625197/233625556-a308183d-c02b-4153-86be-990d2919b163.png)
> 
> 

Hi, I checked out our AmigaOS. Not sure if there is any issue that we couldn't find the info as the following screenshot shows:
![image](https://user-images.githubusercontent.com/17966131/233746493-35430310-f06f-4884-851d-52c9e220e6f7.jpeg)

Can I check the OS version inside the Amiga by command line?

**Comment by shaoshuaizyk** [comment]
We tried to update the AmigaOS today:![image](https://user-images.githubusercontent.com/17966131/233770942-dff8ebfc-a2b4-4688-9ba8-ea5d20f50c35.jpeg)

It seems that it updated successfully(maybe not?) but we still couldn't check the system version in the setting page even if we restarted the amiga after 10 mins.
Not sure if we update the system. Could you help us with this issue?

Thanks!

**Comment by yuhualong508** [comment]
Our AmigaOS might be still in v1.0.0. After we type the curl command the system UI didn't changes. How we can update the AmigaOS to the v1.1.0 or new version from the v 1.0.0?Thanks.

**Comment by yuhualong508** [comment]
Yeah Thanks.
What’s the best time for you today to help us update the system

Kyle Coble ***@***.***>于2023年4月24日 周一上午7:41写道：
